#!/usr/bin/env bash

set -uexo pipefail

sed -i 's|#LockLayering.*|LockLayering=true|' /etc/rpm-ostreed.conf

dnf -y install 'dnf5-command(copr)'
dnf -y copr enable neilalexander/yggdrasil-go
dnf -y install yggdrasil
systemctl enable yggdrasil.service

dnf -y install qemu-guest-agent
dnf -y install zram-generator-defaults
dnf -y install tmux vim fish

for m in /ctx/modules/*/ ; do
    env --chdir="$m" ./build
done
