#!/usr/bin/env bash

set -uexo pipefail

sed -i 's|#LockLayering.*|LockLayering=true|' /etc/rpm-ostreed.conf

dnf -y install 'dnf5-command(copr)'
dnf -y copr enable neilalexander/yggdrasil-go
dnf -y install yggdrasil
systemctl enable yggdrasil.service

dnf -y install qemu-guest-agent

dnf -y install zram-generator-defaults

dnf -y install firewalld fail2ban
systemctl enable fail2ban.service
sed -i 's|DefaultZone=public|DefaultZone=custom|' /etc/firewalld/firewalld.conf

dnf -y install tmux vim fish

# to fend off lazy botnets probing the 22nd port
semanage port -a -t ssh_port_t -p tcp 1022
