#!/usr/bin/env bash

set -uexo pipefail

sed -i 's|#LockLayering.*|LockLayering=true|' /etc/rpm-ostreed.conf

dnf -y install 'dnf5-command(copr)'

dnf -y install qemu-guest-agent
dnf -y install zram-generator-defaults
dnf -y install tmux vim fish

modules=$(ls -1 /ctx/profiles/${BUILD_PROFILE}/)
for m in $modules ; do
    env --chdir="/ctx/modules/$m" ./build
done
